FROM python:3.10-slim
WORKDIR /app
ADD ./Deploy/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
ADD Deploy .
ADD ./Dataset/Images ./Dataset/Images
RUN  apt-get update && apt-get install -y libgl1-mesa-glx libopencv-dev
CMD ["python", "Main.py"]
